export interface SampleMediaItem {
  type: "MOVIE" | "PHOTO" | "FAMILY_VIDEO" | "FILE";
  status: "READY";
  title_en: string;
  title_te: string;
  titleEn: string;
  titleTe: string;
  originalName: string;
  year: number;
  durationSeconds?: number;
  durationSec?: number;
  sizeBytes: bigint;
  mimeType: string;
  originalKey: string;
  storageKey: string;
  posterKey?: string | null;
  thumbKey?: string | null;
  checksumSha256: string;
}

export const SAMPLE_MEDIA: SampleMediaItem[] = [
  // 15 Classic & Modern Telugu Movies
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Maya Bazaar",
    title_te: "మాయాబజార్",
    titleEn: "Maya Bazaar",
    titleTe: "మాయాబజార్",
    originalName: "Maya.Bazaar.1957.1080p.NF.WEB-DL.mp4",
    year: 1957,
    durationSeconds: 11100,
    durationSec: 11100,
    sizeBytes: BigInt(3400000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1957/media_mayabazaar/Maya_Bazaar.mp4",
    storageKey: "originals/MOVIE/1957/media_mayabazaar/Maya_Bazaar.mp4",
    posterKey: "posters/media_mayabazaar.jpg",
    checksumSha256: "sha256_mayabazaar_1957",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Missamma",
    title_te: "మిస్సమ్మ",
    titleEn: "Missamma",
    titleTe: "మిస్సమ్మ",
    originalName: "Missamma.1955.720p.HD.mp4",
    year: 1955,
    durationSeconds: 9900,
    durationSec: 9900,
    sizeBytes: BigInt(2200000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1955/media_missamma/Missamma.mp4",
    storageKey: "originals/MOVIE/1955/media_missamma/Missamma.mp4",
    checksumSha256: "sha256_missamma_1955",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Gundamma Katha",
    title_te: "గుండమ్మ కథ",
    titleEn: "Gundamma Katha",
    titleTe: "గుండమ్మ కథ",
    originalName: "Gundamma.Katha.1962.1080p.mp4",
    year: 1962,
    durationSeconds: 10200,
    durationSec: 10200,
    sizeBytes: BigInt(2800000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1962/media_gundamma/Gundamma_Katha.mp4",
    storageKey: "originals/MOVIE/1962/media_gundamma/Gundamma_Katha.mp4",
    checksumSha256: "sha256_gundamma_1962",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Sankarabharanam",
    title_te: "శంకరాభరణం",
    titleEn: "Sankarabharanam",
    titleTe: "శంకరాభరణం",
    originalName: "Sankarabharanam.1980.Remastered.mp4",
    year: 1980,
    durationSeconds: 8700,
    durationSec: 8700,
    sizeBytes: BigInt(2400000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1980/media_sankarabharanam/Sankarabharanam.mp4",
    storageKey: "originals/MOVIE/1980/media_sankarabharanam/Sankarabharanam.mp4",
    checksumSha256: "sha256_sankarabharanam_1980",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Sagara Sangamam",
    title_te: "సాగర సంగమం",
    titleEn: "Sagara Sangamam",
    titleTe: "సాగర సంగమం",
    originalName: "Sagara.Sangamam.1983.1080p.mp4",
    year: 1983,
    durationSeconds: 9420,
    durationSec: 9420,
    sizeBytes: BigInt(3100000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1983/media_sagarasangamam/Sagara_Sangamam.mp4",
    storageKey: "originals/MOVIE/1983/media_sagarasangamam/Sagara_Sangamam.mp4",
    checksumSha256: "sha256_sagarasangamam_1983",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Geethanjali",
    title_te: "గీతాంజలి",
    titleEn: "Geethanjali",
    titleTe: "గీతాంజలి",
    originalName: "Geethanjali.1989.1080p.WEB-DL.mp4",
    year: 1989,
    durationSeconds: 9000,
    durationSec: 9000,
    sizeBytes: BigInt(2700000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1989/media_geethanjali/Geethanjali.mp4",
    storageKey: "originals/MOVIE/1989/media_geethanjali/Geethanjali.mp4",
    checksumSha256: "sha256_geethanjali_1989",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Annamayya",
    title_te: "అన్నమయ్య",
    titleEn: "Annamayya",
    titleTe: "అన్నమయ్య",
    originalName: "Annamayya.1997.Telugu.DVDRip.mp4",
    year: 1997,
    durationSeconds: 10440,
    durationSec: 10440,
    sizeBytes: BigInt(3200000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/1997/media_annamayya/Annamayya.mp4",
    storageKey: "originals/MOVIE/1997/media_annamayya/Annamayya.mp4",
    checksumSha256: "sha256_annamayya_1997",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Malliswari",
    title_te: "మల్లీశ్వరి",
    titleEn: "Malliswari",
    titleTe: "మల్లీశ్వరి",
    originalName: "Malliswari.2004.HDTV.720p.mp4",
    year: 2004,
    durationSeconds: 9300,
    durationSec: 9300,
    sizeBytes: BigInt(2500000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2004/media_malliswari/Malliswari.mp4",
    storageKey: "originals/MOVIE/2004/media_malliswari/Malliswari.mp4",
    checksumSha256: "sha256_malliswari_2004",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Athadu",
    title_te: "అతడు",
    titleEn: "Athadu",
    titleTe: "అతడు",
    originalName: "Athadu.2005.1080p.AAC.mp4",
    year: 2005,
    durationSeconds: 10500,
    durationSec: 10500,
    sizeBytes: BigInt(3800000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2005/media_athadu/Athadu.mp4",
    storageKey: "originals/MOVIE/2005/media_athadu/Athadu.mp4",
    checksumSha256: "sha256_athadu_2005",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Bommarillu",
    title_te: "బొమ్మరిల్లు",
    titleEn: "Bommarillu",
    titleTe: "బొమ్మరిల్లు",
    originalName: "Bommarillu.2006.Telugu.HD.mp4",
    year: 2006,
    durationSeconds: 9600,
    durationSec: 9600,
    sizeBytes: BigInt(2900000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2006/media_bommarillu/Bommarillu.mp4",
    storageKey: "originals/MOVIE/2006/media_bommarillu/Bommarillu.mp4",
    checksumSha256: "sha256_bommarillu_2006",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Manam",
    title_te: "మనం",
    titleEn: "Manam",
    titleTe: "మనం",
    originalName: "Manam.2014.1080p.BluRay.mp4",
    year: 2014,
    durationSeconds: 9780,
    durationSec: 9780,
    sizeBytes: BigInt(3500000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2014/media_manam/Manam.mp4",
    storageKey: "originals/MOVIE/2014/media_manam/Manam.mp4",
    checksumSha256: "sha256_manam_2014",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Baahubali The Beginning",
    title_te: "బాహుబలి",
    titleEn: "Baahubali The Beginning",
    titleTe: "బాహుబలి",
    originalName: "Baahubali.The.Beginning.2015.1080p.mp4",
    year: 2015,
    durationSeconds: 9540,
    durationSec: 9540,
    sizeBytes: BigInt(4100000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2015/media_baahubali1/Baahubali1.mp4",
    storageKey: "originals/MOVIE/2015/media_baahubali1/Baahubali1.mp4",
    checksumSha256: "sha256_baahubali_2015",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Mahanati",
    title_te: "మహానటి",
    titleEn: "Mahanati",
    titleTe: "మహానటి",
    originalName: "Mahanati.2018.1080p.NF.WEB-DL.mp4",
    year: 2018,
    durationSeconds: 10620,
    durationSec: 10620,
    sizeBytes: BigInt(4300000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2018/media_mahanati/Mahanati.mp4",
    storageKey: "originals/MOVIE/2018/media_mahanati/Mahanati.mp4",
    checksumSha256: "sha256_mahanati_2018",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Jersey",
    title_te: "జెర్సీ",
    titleEn: "Jersey",
    titleTe: "జెర్సీ",
    originalName: "Jersey.2019.Telugu.1080p.WEBRip.mp4",
    year: 2019,
    durationSeconds: 9600,
    durationSec: 9600,
    sizeBytes: BigInt(3200000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2019/media_jersey/Jersey.mp4",
    storageKey: "originals/MOVIE/2019/media_jersey/Jersey.mp4",
    checksumSha256: "sha256_jersey_2019",
  },
  {
    type: "MOVIE",
    status: "READY",
    title_en: "Sita Ramam",
    title_te: "సీతా రామం",
    titleEn: "Sita Ramam",
    titleTe: "సీతా రామం",
    originalName: "Sita.Ramam.2022.1080p.AMZN.WEB-DL.mp4",
    year: 2022,
    durationSeconds: 9780,
    durationSec: 9780,
    sizeBytes: BigInt(3900000000),
    mimeType: "video/mp4",
    originalKey: "originals/MOVIE/2022/media_sitaramam/Sita_Ramam.mp4",
    storageKey: "originals/MOVIE/2022/media_sitaramam/Sita_Ramam.mp4",
    checksumSha256: "sha256_sitaramam_2022",
  },

  // 8 Family Photos
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Sankranti Celebrations 2024",
    title_te: "సంక్రాంతి వేడుకలు 2024",
    titleEn: "Sankranti Celebrations 2024",
    titleTe: "సంక్రాంతి వేడుకలు 2024",
    originalName: "IMG_20240115_093012.jpg",
    year: 2024,
    sizeBytes: BigInt(4200000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2024/media_sankranti24/IMG_20240115.jpg",
    storageKey: "originals/PHOTO/2024/media_sankranti24/IMG_20240115.jpg",
    thumbKey: "thumbs/media_sankranti24.webp",
    checksumSha256: "sha256_sankranti_2024",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Tirupati Family Darshanam",
    title_te: "తిరుపతి దర్శనం",
    titleEn: "Tirupati Family Darshanam",
    titleTe: "తిరుపతి దర్శనం",
    originalName: "Tirupati_Trip_2023.jpg",
    year: 2023,
    sizeBytes: BigInt(5100000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2023/media_tirupati/Tirupati_Trip.jpg",
    storageKey: "originals/PHOTO/2023/media_tirupati/Tirupati_Trip.jpg",
    thumbKey: "thumbs/media_tirupati.webp",
    checksumSha256: "sha256_tirupati_2023",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Amma 70th Birthday",
    title_te: "అమ్మ 70వ పుట్టినరోజు",
    titleEn: "Amma 70th Birthday",
    titleTe: "అమ్మ 70వ పుట్టినరోజు",
    originalName: "Amma_70th_Birthday.jpg",
    year: 2022,
    sizeBytes: BigInt(3800000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2022/media_ammabday/Amma_Birthday.jpg",
    storageKey: "originals/PHOTO/2022/media_ammabday/Amma_Birthday.jpg",
    thumbKey: "thumbs/media_ammabday.webp",
    checksumSha256: "sha256_ammabday_2022",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Family Housewarming (Gruhapravesam)",
    title_te: "గృహప్రవేశం",
    titleEn: "Family Housewarming (Gruhapravesam)",
    titleTe: "గృహప్రవేశం",
    originalName: "Gruhapravesam_Group.jpg",
    year: 2021,
    sizeBytes: BigInt(4900000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2021/media_gruhapravesam/Housewarming.jpg",
    storageKey: "originals/PHOTO/2021/media_gruhapravesam/Housewarming.jpg",
    thumbKey: "thumbs/media_gruhapravesam.webp",
    checksumSha256: "sha256_gruhapravesam_2021",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Deepavali Family Portrait",
    title_te: "దీపావళి కుటుంబ ఫోటో",
    titleEn: "Deepavali Family Portrait",
    titleTe: "దీపావళి కుటుంబ ఫోటో",
    originalName: "Diwali_2023_Family.jpg",
    year: 2023,
    sizeBytes: BigInt(4600000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2023/media_diwali23/Diwali_Family.jpg",
    storageKey: "originals/PHOTO/2023/media_diwali23/Diwali_Family.jpg",
    thumbKey: "thumbs/media_diwali23.webp",
    checksumSha256: "sha256_diwali_2023",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Garden Mango Harvest",
    title_te: "తోట మామిడి పండ్ల కోత",
    titleEn: "Garden Mango Harvest",
    titleTe: "తోట మామిడి పండ్ల కోత",
    originalName: "Mango_Harvest_2023.jpg",
    year: 2023,
    sizeBytes: BigInt(3200000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2023/media_mango23/Mango_Harvest.jpg",
    storageKey: "originals/PHOTO/2023/media_mango23/Mango_Harvest.jpg",
    thumbKey: "thumbs/media_mango23.webp",
    checksumSha256: "sha256_mango_2023",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Granddaughter First Birthday",
    title_te: "మనవరాలి మొదటి పుట్టినరోజు",
    titleEn: "Granddaughter First Birthday",
    titleTe: "మనవరాలి మొదటి పుట్టినరోజు",
    originalName: "Ananya_1st_Bday.jpg",
    year: 2020,
    sizeBytes: BigInt(4100000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2020/media_ananya1st/Ananya_Bday.jpg",
    storageKey: "originals/PHOTO/2020/media_ananya1st/Ananya_Bday.jpg",
    thumbKey: "thumbs/media_ananya1st.webp",
    checksumSha256: "sha256_ananya_2020",
  },
  {
    type: "PHOTO",
    status: "READY",
    title_en: "Family Reunion Hyderabad",
    title_te: "హైదరాబాద్ కుటుంబ కలయిక",
    titleEn: "Family Reunion Hyderabad",
    titleTe: "హైదరాబాద్ కుటుంబ కలయిక",
    originalName: "Reunion_Hyd_2019.jpg",
    year: 2019,
    sizeBytes: BigInt(5400000),
    mimeType: "image/jpeg",
    originalKey: "originals/PHOTO/2019/media_reunion19/Reunion_Hyd.jpg",
    storageKey: "originals/PHOTO/2019/media_reunion19/Reunion_Hyd.jpg",
    thumbKey: "thumbs/media_reunion19.webp",
    checksumSha256: "sha256_reunion_2019",
  },

  // 5 Family Videos
  {
    type: "FAMILY_VIDEO",
    status: "READY",
    title_en: "Amma Singing Annamayya Keerthana",
    title_te: "అమ్మ అన్నమయ్య కీర్తన గానం",
    titleEn: "Amma Singing Annamayya Keerthana",
    titleTe: "అమ్మ అన్నమయ్య కీర్తన గానం",
    originalName: "VID_20231012_Amma_Keerthana.mp4",
    year: 2023,
    durationSeconds: 420,
    durationSec: 420,
    sizeBytes: BigInt(180000000),
    mimeType: "video/mp4",
    originalKey: "originals/FAMILY_VIDEO/2023/media_keerthana/Amma_Keerthana.mp4",
    storageKey: "originals/FAMILY_VIDEO/2023/media_keerthana/Amma_Keerthana.mp4",
    checksumSha256: "sha256_keerthana_2023",
  },
  {
    type: "FAMILY_VIDEO",
    status: "READY",
    title_en: "Sankranti Rangoli (Muggulu) Making",
    title_te: "సంక్రాంతి ముగ్గుల వీడియో",
    titleEn: "Sankranti Rangoli (Muggulu) Making",
    titleTe: "సంక్రాంతి ముగ్గుల వీడియో",
    originalName: "Sankranti_Muggulu_2024.mp4",
    year: 2024,
    durationSeconds: 680,
    durationSec: 680,
    sizeBytes: BigInt(320000000),
    mimeType: "video/mp4",
    originalKey: "originals/FAMILY_VIDEO/2024/media_muggulu/Muggulu_2024.mp4",
    storageKey: "originals/FAMILY_VIDEO/2024/media_muggulu/Muggulu_2024.mp4",
    checksumSha256: "sha256_muggulu_2024",
  },
  {
    type: "FAMILY_VIDEO",
    status: "READY",
    title_en: "Grandchildren Dance Performance",
    title_te: "పిల్లల డ్యాన్స్ ప్రదర్శన",
    titleEn: "Grandchildren Dance Performance",
    titleTe: "పిల్లల డ్యాన్స్ ప్రదర్శన",
    originalName: "Kids_Dance_Function.mp4",
    year: 2022,
    durationSeconds: 510,
    durationSec: 510,
    sizeBytes: BigInt(240000000),
    mimeType: "video/mp4",
    originalKey: "originals/FAMILY_VIDEO/2022/media_dance/Kids_Dance.mp4",
    storageKey: "originals/FAMILY_VIDEO/2022/media_dance/Kids_Dance.mp4",
    checksumSha256: "sha256_kidsdance_2022",
  },
  {
    type: "FAMILY_VIDEO",
    status: "READY",
    title_en: "Village Farmhouse Walkthrough",
    title_te: "ఊరి పొలం, తోట నడక",
    titleEn: "Village Farmhouse Walkthrough",
    titleTe: "ఊరి పొలం, తోట నడక",
    originalName: "Farmhouse_Walk_2021.mp4",
    year: 2021,
    durationSeconds: 890,
    durationSec: 890,
    sizeBytes: BigInt(450000000),
    mimeType: "video/mp4",
    originalKey: "originals/FAMILY_VIDEO/2021/media_farmhouse/Farmhouse_Walk.mp4",
    storageKey: "originals/FAMILY_VIDEO/2021/media_farmhouse/Farmhouse_Walk.mp4",
    checksumSha256: "sha256_farmhouse_2021",
  },
  {
    type: "FAMILY_VIDEO",
    status: "READY",
    title_en: "Family Cooking Tradition (Avakaya)",
    title_te: "ఆవకాయ తయారీ సంప్రదాయం",
    titleEn: "Family Cooking Tradition (Avakaya)",
    titleTe: "ఆవకాయ తయారీ సంప్రదాయం",
    originalName: "Avakaya_Making_2023.mp4",
    year: 2023,
    durationSeconds: 1200,
    durationSec: 1200,
    sizeBytes: BigInt(620000000),
    mimeType: "video/mp4",
    originalKey: "originals/FAMILY_VIDEO/2023/media_avakaya/Avakaya_Making.mp4",
    storageKey: "originals/FAMILY_VIDEO/2023/media_avakaya/Avakaya_Making.mp4",
    checksumSha256: "sha256_avakaya_2023",
  },

  // 2 Other Files
  {
    type: "FILE",
    status: "READY",
    title_en: "Traditional Telugu Recipes Book",
    title_te: "సాంప్రదాయ తెలుగు వంటకాల పుస్తకం",
    titleEn: "Traditional Telugu Recipes Book",
    titleTe: "సాంప్రదాయ తెలుగు వంటకాల పుస్తకం",
    originalName: "Telugu_Vantalu_Book.pdf",
    year: 2022,
    sizeBytes: BigInt(15000000),
    mimeType: "application/pdf",
    originalKey: "originals/FILE/2022/media_recipes/Telugu_Recipes.pdf",
    storageKey: "originals/FILE/2022/media_recipes/Telugu_Recipes.pdf",
    checksumSha256: "sha256_recipes_2022",
  },
  {
    type: "FILE",
    status: "READY",
    title_en: "Family Property Documents Scan",
    title_te: "కుటుంబ ఆస్తి పత్రాల స్కాన్",
    titleEn: "Family Property Documents Scan",
    titleTe: "కుటుంబ ఆస్తి పత్రాల స్కాన్",
    originalName: "Property_Documents_Scan.pdf",
    year: 2021,
    sizeBytes: BigInt(8500000),
    mimeType: "application/pdf",
    originalKey: "originals/FILE/2021/media_property/Property_Documents.pdf",
    storageKey: "originals/FILE/2021/media_property/Property_Documents.pdf",
    checksumSha256: "sha256_property_2021",
  },
];
